### PR TITLE
feat: generate classes with `!important`

### LINKED ISSUE #32: Leverage `!important` in Class Definitions
In the front-end guild meeting today, it was mentioned that we can't really use Tailwind classes to override default styles that are being applied from elsewhere.

Tailwind has the option to generate styles with `!important`, which would help with this.

`!important` shouldn't be necessary normally in Tailwind, but because we are introducing it to a legacy application, it would actually be a good fit for our use-case!

### PR DESCRIPTION
**Pull request by alexlafroscia**
Closes #32

### CODE REVIEW

**Comment by nicksteffens** [comment]
While I'm 100% for this change I do want to call out this will unblock most users while we expected users to clean up the unused css, it is a risk for @alexlafroscia and myself to cleanup later. 

This also provides a good reason to NOT include any new css unless a very good reason.

CC: @spencer516 @movableink/design-systems

**Comment by alexlafroscia** [comment]
Interestingly, this generates about 40kb more CSS than before. Not a problem, but worth noting.

Compression should do a good job of taking care of that, though; `!important` repeated over and over is easy to compress.

I really want to get something set up here that can report the file sizes (normal, minified, gzipped+minified) and how it's changed since `master`.

**Comment by spencer516** [comment]
@nicksteffens — it does seem a little bit like a forcing function to adopt Tailwind, for better or for worse. 

But, how could it cause more cleanup work in the future? Would someone have to use `!important` to override something that came from Tailwind or something?

**Comment by alexlafroscia** [comment]
I think the idea is that by making it easy to just slap on a Tailwind class (that includes `!important`) and call it a day, it is easier for people to _not_ go and actually clean stuff up that's causing them to need a `!important` in the first place.

If we _don't_ give people `!important` then it really highlights where it's hard to use Tailwind, which are signs that there's a deeper CSS problem that needs to be cleaned up.

**Comment by nicksteffens** [comment]
@spencer516 

Whatever class / selector with `!important` is last and/or more specific in the stylesheet will be correct. Following color examples:
https://jsfiddle.net/v91c2qoj/

**Comment by alexlafroscia** [comment]
Rebased in to view the file size diff 😁

**Comment by alexlafroscia** [comment]
^ Sized appear the same because I merged the PR before it finished running.

**Pull request merged**
